stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/asp
        - cp -frv ./include/asp $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libasp.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libasp.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_asp $UT_PATH

        - mkdir -p $BIN_PATH
        - cp -fv release/aspview $BIN_PATH

    only:
        - master

cmd:
    stage: trigger
    script:
        - curl -X POST -F token=187e8c273995b3f26231a84f72e6e3 -F ref=master $GITLAB_URL/api/v4/projects/14/trigger/pipeline
    only:
        - master
